export const NO_COLLISIONS = 0; // 0000
export const HORIZONTAL_COLLISION = 1; // 0001
export const BOTTOM_COLLISION = 2; // 0010
export const GUTTER_COLLISION = 4; // 0100
export const TOP_COLLISION = 8; // 1000
export const MAX_COLLISION = HORIZONTAL_COLLISION | BOTTOM_COLLISION | GUTTER_COLLISION | TOP_COLLISION; // 1111
